### ISSUE TITLE
User Interface Optimisation

### ISSUE THREAD

**Issue by maxgerber** [MAM-Apps/MAM-Events#65]
We have implemented some things to make the UI more intuitive. For instance, we have added a splash screen so the user understands they need to wait before the map is ready, and in this splash screen we have created a basic instructions. However, there are further optimisations we could make to allow the user experience to be crystal clear 🔮 .

- [ ] We should consider changing the markers on Google Maps to something smaller, like a coloured circle. When our events are spiderified, it can look a bit cluttered to have the google marker.
- [ ] more responsive time buttons, where the font increases past a certain point, and the margins between the buttons slightly increases also, which will make for a less cluttered interface.
- [ ] Update the info windows so they are more attractive, and display more readable information at a glance. We wish to see information on date, people attending, and a cover photo which will render in the window like a mini facebook event view.
- [ ] Change the styling on the Error Bar to incorporate a viewport-width wide frosted glass effect with larger more readable text. At the moment the information hovers in dark red on a dark grey background and is not styled at all. We need to make it look like part of the application.
- [ ] Every single time an info window is opened, it is required, but not necessarily obvious, that we need to close them with the 'X' in the top right. It would be more intuitive to be able to close these windows by clicking anywhere else on the map, and to close windows once we open another. This way we won't get window-clash.
